version: '3.8'

services:
  server:
    image: cr.yandex/crp57d2amknkinm23mfn/weather-app-server:latest
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./postgresql/root.crt:/root/.postgresql/root.crt:ro
    networks:
      - weather-network
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped

  client:
    image: cr.yandex/crp57d2amknkinm23mfn/weather-app-client:latest
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - weather-network
    restart: unless-stopped

networks:
  weather-network:
    driver: bridge
